 
-
RESTORE DATABASE[AUTOPARTNER] FROM DISK = '/srv/backup/diff/AUTOPARTNER.bak' WITH RECOVERY,
REPLACE, STATS = 5
RESTORE DATABASE[KR_L_WOJCIECH_LURK] FROM DISK = '/srv/backup/diff/KR_L_WOJCIECH_LURK.bak' WITH RECOVERY,
REPLACE, STATS = 5

(2 rows affected)
